# Generated by Django 3.2 on 2021-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210423_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image 2'),
        ),
    ]
