# Generated by Django 3.2 on 2021-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210424_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertaiment',
            name='category',
        ),
        migrations.AddField(
            model_name='entertaiment',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
